### ISSUE TITLE
ConfigSpeed adjustments don't seem to affect the block speed ingame

### ISSUE THREAD

**Issue by StaticSapphic** [MapperTV/blockrunner#1]
I was building a list of blocks when I noticed the grass and gravel paths weren't affecting the player's speed. After some testing, I swapped the blocks in [config_b] (which originally consisted of grass and gravel paths) and [config_c]. When this happened, the grass and gravel paths started working, and the blocks that were originally in [config_b] stopped working. The only conclusion I can draw from this is that the mod refuses to accept that config c, d and e are enabled.

**Blockrunner Version:** blockrunner-1.16.4-1.0.0.0
**Mapper Base Version:** mapperbase-1.16.4-2.3.0.0
**Forge Version:** forge-35.1.13

Below is the contents of my config file. No errors were logged to console
```
#Config A
[config_a]
	#Enable config A? [true / false]
	configAEnabled = true
	#List of blocks for config A (format is "modid:block_name")
	configABlocks = ["minecraft:cobblestone"]
	#Speed bonus [default: 0.15]
	#Range: 0.01 ~ 100.0
	configASpeed = 0.15

#Config B
[config_b]
	#Enable config B? [true / false]
	configBEnabled = true
	#List of blocks for config B (format is "modid:block_name")
	configBBlocks = ["minecraft:grass_path", "buildersaddition:gravel_path"]
	#Speed bonus [default: 0.3]
	#Range: 0.01 ~ 100.0
	configBSpeed = 0.25

#Config C
[config_c]
	#Enable config C? [true / false]
	configCEnabled = true
	#List of blocks for config C (format is "modid:block_name")
	configCBlocks = ["cfm:rock_path", "minecraft:polished_andesite", "minecraft:polished_diorite", "minecraft:polished_granite", "minecraft:polished_blackstone", "embellishcraft:polished_basalt", "embellishcraft:polished_slate", "embellishcraft:polished_marble", "embellishcraft:polished_gneiss", "embellishcraft:polished_jade", "embellishcraft:polished_larvikite", "embellishcraft:polished_sandstone", "embellishcraft:polished_red_sandstone", "embellishcraft:polished_terracotta", "minecraft:polished_andesite_stairs", "minecraft:polished_diorite_stairs", "minecraft:polished_granite_stairs", "minecraft:polished_blackstone_stairs", "embellishcraft:polished_basalt_stairs", "embellishcraft:polished_slate_stairs", "embellishcraft:polished_marble_stairs", "embellishcraft:polished_gneiss_stairs", "embellishcraft:polished_jade_stairs", "embellishcraft:polished_larvikite_stairs", "embellishcraft:polished_sandstone_stairs", "embellishcraft:polished_red_sandstone_stairs", "embellishcraft:polished_terracotta_stairs", "minecraft:polished_andesite_slab", "minecraft:polished_diorite_slab", "minecraft:polished_granite_slab", "minecraft:polished_blackstone_slab", "embellishcraft:polished_basalt_slab", "embellishcraft:polished_slate_slab", "embellishcraft:polished_marble_slab", "embellishcraft:polished_gneiss_slab", "embellishcraft:polished_jade_slab", "embellishcraft:polished_larvikite_slab", "embellishcraft:polished_sandstone_slab", "embellishcraft:polished_red_sandstone_slab", "embellishcraft:polished_terracotta_slab", "masonry:stonepolished", "masonry:darkprismarinepolished", "masonry:prismarinepolished", "masonry:stonepolishedslab", "masonry:darkprismarinepolishedslab", "masonry:prismarinepolishedslab", "quark:polished_marble", "quark:polished_limestone", "quark:polished_jasper", "quark:polished_slate", "quark:polished_voidstone", "quark:polished_marble_stairs", "quark:polished_limestone_stairs", "quark:polished_jasper_stairs", "quark:polished_slate_stairs", "quark:polished_voidstone_stairs", "quark:polished_marble_slab", "quark:polished_limestone_slab", "quark:polished_jasper_slab", "quark:polished_slate_slab", "quark:polished_voidstone_slab", "minecraft:smooth_stone", "minecraft:smooth_stone_stairs", "minecraft:smooth_stone_slab", "amb:smooth_purpur_block", "amb:smooth_purpur_stairs", "amb:smooth_purpur_slab"]
	#Speed bonus
	#Range: 0.01 ~ 100.0
	configCSpeed = 0.2

#Config D
[config_d]
	#Enable config D? [true / false]
	configDEnabled = true
	#List of blocks for config D (format is "modid:block_name")
	configDBlocks = ["embellishcraft:basalt_paving", "embellishcraft:slate_paving", "embellishcraft:marble_paving", "embellishcraft:gneiss_paving", "embellishcraft:jade_paving", "embellishcraft:larvikite_paving", "embellishcraft:andesite_paving", "embellishcraft:diorite_paving", "embellishcraft:granite_paving", "embellishcraft:sandstone_paving", "embellishcraft:red_sandstone_paving", "embellishcraft:terracotta_paving", "embellishcraft:basalt_paving_stones", "embellishcraft:slate_paving_stones", "embellishcraft:marble_paving_stones", "embellishcraft:gneiss_paving_stones", "embellishcraft:jade_paving_stones", "embellishcraft:larvikite_paving_stones", "embellishcraft:andesite_paving_stones", "embellishcraft:diorite_paving_stones", "embellishcraft:granite_paving_stones", "embellishcraft:sandstone_paving_stones", "embellishcraft:red_sandstone_paving_stones", "embellishcraft:terracotta_paving_stones", "minecraft:dirt"]
	#Speed bonus
	#Range: 0.01 ~ 100.0
	configDSpeed = 0.675

#Config E
[config_e]
	#Enable config E? [true / false]
	configEEnabled = true
	#List of blocks for config E (format is "modid:block_name")
	configEBlocks = ["minecraft:bedrock", "minecraft:obsidian"]
	#Speed bonus
	#Range: 0.01 ~ 100.0
	configESpeed = 0.3
```

**Comment by StaticSapphic** [comment]
I actually have another theory which seems to be plausible: You can't adjust the speed

Because I've attempted to adjust the speeds and although I have no means of measuring, [config_a] will always be slower than [config_b]. Doesn't matter what values I set the speed to, whether it's 0.01, 0.2, 1, 100.

This would also explain why configs c d and e don't work, it isn't because of them being disabled, but rather that they are stuck at a speed of 0.01, which is the default speed for those ones, thus causing them to _appear_ to be disabled

(Changed title from `Mod doesn't seem to acknowledge when [config_c][config_d] and [config_d] are set to true` to `configSpeed adjustments don't seem to affect the block speed ingame` to reflect this

**Comment by MapperTV** [comment]
For some reason the game stopped loading the config value and will always use the default values. It worked fine before, no idea why it doesn't anymore. Even in my dev workspace, without updating Forge, it stopped working.

I'll dig a bit more and see why it doesn't work. It may require a new config file so be sure to backup your own config so you can copy paste the block lists in the new file if I have to change things too much.

**Comment by MapperTV** [comment]
I released a new version that should fix the problem. I also made big changes on how the config file is managed so **be sure to backup your existing file first** to keep your block lists and copy them in the new config file.

Now config is server side which means each save (both single player and server) can have its own config file, allowing unique config per save. you need to create a world first to have the file generated in the serverconfig folder (find it in the save folder). Then you can configure it and copy it to the defaultconfigs folder so it should be applied to all future worlds you create (at least that's how I understood it, useful for modpack makers).

Values also changed a lot, you'll have to reduce them now (0.01 is enough to apply a small boost, above 0.5 it's already quite fast). You can also enter negative value to slow down instead of boosting players.

If another problem appears please report it in another issue.
Thanks.
